---
- name: Deploy Gitea Git Quadlet
  ansible.builtin.template:
    src: gitea.container.j2
    dest: "/home/{{ homelab_user }}/.config/containers/systemd/gitea.container"
    owner: "{{ homelab_user }}"
    group: "{{ homelab_user }}"
    mode: "0644"
  become: true
  notify: Reload systemd user daemon
