FROM registry.fedoraproject.org/fedora:41

ENV container=podman \
    LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN dnf update -y && \
    dnf install -y \
        git \
        curl \
        wget \
        jq \
        tar \
        which \
        sudo \
        shadow-utils \
        openssh-clients \
        python3 \
        python3-pip \
        pipx \
        just \
        findutils \
        bash-completion \
        glibc-langpack-en \
        nu && \
    dnf clean all

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd --gid "${USER_GID}" "${USERNAME}" && \
    useradd --uid "${USER_UID}" --gid "${USER_GID}" -m -s /usr/bin/nu "${USERNAME}" && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/"${USERNAME}" && \
    chmod 0440 /etc/sudoers.d/"${USERNAME}"

USER "${USERNAME}"
ENV PATH="/home/${USERNAME}/.local/bin:${PATH}"

RUN pipx install --include-deps ansible-core && \
    pipx install ansible-navigator && \
    pipx install ansible-lint && \
    pipx install pre-commit && \
    pipx inject ansible-navigator argcomplete

WORKDIR /workspace
