# Core System User & Runtime
homelab_user: "homelab"
homelab_uid: 1001
homelab_gid: 1001
homelab_base_dir: "/var/homelab"

# Network & Ingress
homelab_network_name: "homelab-net"
homelab_network_subnet: "10.89.0.0/24"
homelab_domain: "shooey.xyz"

# Services Port & Subdomain Mappings
cloudflare_tunnel_name: "homelab-edge"

portfolio_container_image: "docker.io/library/nginx:alpine"
portfolio_container_port: 8080
portfolio_subdomain: "{{ homelab_domain }}"

navidrome_container_image: "docker.io/deluan/navidrome:latest"
navidrome_container_port: 4533
navidrome_subdomain: "music.{{ homelab_domain }}"
navidrome_music_dir: "{{ homelab_base_dir }}/navidrome/music"
navidrome_data_dir: "{{ homelab_base_dir }}/navidrome/data"

forgejo_container_image: "codeberg.org/forgejo/forgejo:9-rootless"
forgejo_container_http_port: 3000
forgejo_container_ssh_port: 2222
forgejo_subdomain: "git.{{ homelab_domain }}"
forgejo_data_dir: "{{ homelab_base_dir }}/forgejo/data"

uptime_kuma_container_image: "docker.io/louislam/uptime-kuma:1"
uptime_kuma_container_port: 3001
uptime_subdomain: "status.{{ homelab_domain }}"
uptime_kuma_data_dir: "{{ homelab_base_dir }}/uptime-kuma/data"

rclone_remote_name: "gdrive"
rclone_music_remote_path: "music"
rclone_backup_remote_path: "homelab-backups"
rclone_cache_dir: "/var/cache/rclone"
rclone_config_path: "/etc/rclone/rclone.conf"
