---
- name: Deploy Forgejo Git Quadlet
  ansible.builtin.template:
    src: forgejo.container.j2
    dest: "/home/{{ homelab_user }}/.config/containers/systemd/forgejo.container"
    owner: "{{ homelab_user }}"
    group: "{{ homelab_user }}"
    mode: "0644"
  become: true
  notify: Reload systemd user daemon
